# Generated by Django 3.1.7 on 2021-03-21 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Listen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitarbeiter',
            name='mitarbeiter_bezeichnung',
        ),
    ]
