# Generated by Django 3.1.7 on 2021-04-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listen', '0002_remove_mitarbeiter_mitarbeiter_bezeichnung'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mitarbeiter',
            old_name='mitarbeiter_vorname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='produkt',
            name='produkt_anzahl',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
