# Generated by Django 3.1.7 on 2021-05-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Listen', '0003_auto_20210406_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='produkt_einheit_id_fkey',
        ),
    ]
